micronaut:
  application:
    name: employee-report-backend
  server:
    cors:
      enabled: true
      configurations:
        default:
          allowed-origins:
            - http://localhost:3000
          allowed-methods:
            - GET
            - POST
            - PUT
            - DELETE
          allowed-headers:
            - Content-Type
            - Authorization

datasources:
  default:
    url: jdbc:mysql://localhost:3306/activity_tracker?characterEncoding=UTF-8
    username: swapnil
    password: mysqlswap06
    driver-class-name: com.mysql.cj.jdbc.Driver
    db-type: mysql
    dialect: MYSQL

flyway:
  datasources:
    default:
      enabled: true
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
          show_sql: true
    entity-scan:
      packages: "com.employeereport.entity"

netty:
  default:
    allocator:
      max-order: 3
